[meta]
id = "605fec01-6cbc-4932-8fe8-09b02c6d50f1"
name = "Tracks (Root)"

[format]
plugin = "music-std"
name = "multi-track"

[data.tracks.0]
disabled = false
color = [1.0, 0.4, 0.6, 1.0]

[[data.patterns]]
id = "7931ed81-f5ce-4525-aaf0-41f112e0ed8a"
track = 1
start_on_track_secs = 2.0
slice = [0.0, 3.0]
