[info]
name = "Untitled Project"
license = "MIT"
authors = ["Pedro Braga"]

[editor]
requires_version = "0.0.1"

[path_overrides]
arrangements_dir = "./arrangements"

[[plugins]]
id = "music-core"
path = "./plugins/music-core.so"
