[info]
name = "Untitled Project"
license = "MIT"
authors = ["Pedro Braga"]

[path_overrides]
arrangements_dir = "songs"

[editor]
requires_version = "0.0.1"

[[plugins]]
id = "music-core"
path = "./plugins/music-core.so"
