[package]
name = "cables-macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
cables-core = { path = "../cables-core" }
syn = { version = "2.0.108", features = ["full"] }
quote = "1.0.41"
proc-macro2 = "1.0.103"

[dev-dependencies]
hound = "3.5.1"